# Generated by Django 3.2 on 2023-05-19 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название кия')),
                ('description', models.CharField(max_length=255, verbose_name='Описание кия')),
                ('composition', models.IntegerField(verbose_name='Составность кия')),
                ('structure', models.CharField(max_length=150, verbose_name='Состав кия')),
                ('workshop', models.CharField(max_length=100, verbose_name='Мастерская кия')),
                ('weight', models.IntegerField(verbose_name='Вес кия')),
                ('article', models.IntegerField(verbose_name='Артикул кия')),
                ('price', models.FloatField(verbose_name='Цена кия')),
                ('play', models.CharField(max_length=50, verbose_name='Принадлежность к игре')),
                ('count', models.IntegerField(default=1, verbose_name='Количество кия')),
            ],
            options={
                'verbose_name': 'Кий',
                'verbose_name_plural': 'Кии',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='backend_media/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='cue.cue', verbose_name='Покупка')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
    ]
